### ISSUE TITLE
[bug] Sometimes players are able to cast spell at already dead units.

### ISSUE THREAD

**Issue by Visagalis** [mangosArchives/Mangos-One-server-old#12]
Sometimes players are able to cast spell at already dead units, right after kill sometimes you start castng another spell.

fixed problem with casting spell at already dead target.

<pre>
diff --git a/src/game/Unit.cpp b/src/game/Unit.cpp
index da04012..9e256e4 100644
--- a/src/game/Unit.cpp
+++ b/src/game/Unit.cpp
@@ -812,6 +812,7 @@ uint32 Unit::DealDamage(Unit *pVictim, uint32 damage, CleanDamage const* cleanDa
                 if (BattleGround *bg = player_tap->GetBattleGround())
                     bg->HandleKillUnit((Creature*)pVictim, player_tap);
         }
+        CombatStop(true);
     }
     else                                                    // if (health <= damage)
     {
</pre>

**Comment by DomGries** [comment]
Thanks. Any idea why its not a problem on master?

**Comment by Visagalis** [comment]
i don't know. I haven't checked on master.

**Comment by DomGries** [comment]
No need to close it :P

**Comment by Visagalis** [comment]
oh my bad, i accidentaly clicked comment and close :D

**Comment by Visagalis** [comment]
my patch has bug, seems like only players need to combatstop(true);
-        if (GetTypeId() == TYPEID_PLAYER)
-            CombatStop(true);

otherwise npcs doesn't reset when they kill player.
