### ISSUE TITLE
[bug] mana tap

### ISSUE THREAD

**Issue by Visagalis** [mangosArchives/Mangos-One-server-old#14]
You should be able to cast Mana tap (http://old.wowhead.com/spell=28734) only to npcs which have MANA? but you can cast it on anyone instead. I couldn't find a way to fix this one.

**Comment by DomGries** [comment]
I think this should be added to CanCast function in spell.cpp but I am not really familiar with the spellsystem. Just keep in mind that it can be used even if the player/creature has currently 0 mana but theoretically has mana (has a mana bar).
