### ISSUE TITLE
[s1298] Totem/Relic etc swapping should "not" tirgger GCD

### ISSUE THREAD

**Issue by Nighoo** [mangosArchives/Mangos-One-server-old#17]
Commit s1298 is wrong in mangos one. Triggering the GCD was no feature in TBC.

**Comment by DomGries** [comment]
any news about this one as i couldnt find any info related to it anywhere? I even searched through all wotlk patch notes

**Comment by vermie** [comment]
I used to swap my librams all the time.  http://www.wowhead.com/item=33502/libram-of-mending#comments:id=185695

They did change it in2.4 so that you couldn't swap mid-cast.  But you can swap before or after with no GCD.

**Comment by DomGries** [comment]
Thanks for that info

Actually it was changed in 2.4.3, http://www.wowwiki.com/Patch_2.4.3 - "Equipping an item will now cancel any spell cast currently in progress."

Wonder if that works already

**Comment by DomGries** [comment]
Reverted in [s1434] and therefore fixed. Thanks

**Comment by DomGries** [comment]
Reopened due to Midna's PM:

```
Swapping relic/libram in combat should cause GCD.

You can however:
/cast spell
/equip other libram

as it should only create a GCD, not obay one in process.
```

http://www.wowhead.com/item=33508/idol-of-budding-life#comments
By Remedy (394 – 9) on 2007/12/02 (Patch 2.3.0) wrote:

```
I'm not sure if it is a global cooldown, but there is a pause that is created from switching relics in this manner while in combat. It is very annoying
```

By Beargrylls (191 – 3·2) on 2007/12/05 (Patch 2.3.0) wrote:

```
Changing Idols triggers global cooldown. Global cooldown + instant casts = no thanks on this idol.
```

By Sahrish (4,251 – 6·26) on 2007/12/13 (Patch 2.3.0) wrote:

```
Beargrylls is correct; after changing weapons or relics, you get a 1.5 second global cooldown before you can cast anything afterwards. This is often neglible on spells with a cast time over 1.5 seconds, since you can swap items midcast, but since Rejuvenation and Lifebloom are instant cast, you would have to initiate the cooldown -before- you cast...meaning using the above stated macros will only slow down your casting, which can be very bad if you are maintaining Lifebloom on multiple targets.

However, if you're healing a single target and can easily take the time to swap idols, then by all means go for it.
```

**Comment by DomGries** [comment]
Reverted revertion of GCD in [s1452]. Totem/Relic should indeed trigger GCD...
