### ISSUE TITLE
SMSG_GAMEOBJECT_QUERY_RESPONSE

### ISSUE THREAD

**Issue by DomGries** [mangosArchives/Mangos-One-server-old#19]
I came to believe that SMSG_GAMEOBJECT_QUERY_RESPONSE does not have the gameobject size field in 2.4.3 .

This info is based on many 2.4.1 sniffs so I am pretty sure but not 100% sure. OregonCore and TrinityCore1 also dont have that field.

It was added in http://mangos.svn.sourceforge.net/viewvc/mangos/trunk/src/game/QueryHandler.cpp?r1=6662&r2=6748 . Mangos zero also had that field but correctly removed in later.

Would be nice if someone has more info on that

**Comment by VladimirMangos** [comment]
Can't confirm. but maybe do some experiments with 2/3/4 values with clean WDB?

**Comment by DomGries** [comment]
Alright, I checked the wdb's with help of crackm and verified that on 2.4.3 the size field of gameobjects indeed does exist. Therefore it must have been added in 2.4.2 or 2.4.3 ;)

**Comment by VladimirMangos** [comment]
nice)
