### ISSUE TITLE
Folder "bindings" not in CMakeLists

### ISSUE THREAD

**Issue by Lillecarl** [mangosArchives/Mangos-One-server-old#23]
Well, the title describes it all, the bindings folder are not in the cmakelists.txt, which result in "new people" wont be able to get scriptdev2 to work (since it patches the Cmakelists.txt inside the bindings folder only)

I do not know how to make a patch, but there aint really a hard fix (doh) so anyone with push access to the one repo could probably fix this =)

**Comment by Salja** [comment]
https://github.com/mangos-one/server/blob/master/src/CMakeLists.txt#L29

hmm its in cmake or waht you mean ?

**Comment by Lillecarl** [comment]
Oh sorry, must have been some old dumb change i did to my repo ^^ Im sorry, you can close this one

And thank you for the damn quick answer =)
