### ISSUE TITLE
TYPO

### ISSUE THREAD

**Issue by Lillecarl** [mangosArchives/Mangos-One-server-old#25]
PLAYER_FIELD_LIFETIME_HONORABLE_KILLS is 
PLAYER_FIELD_LIFETIME_HONORBALE_KILLS in mangos ^^,

**Comment by Nighoo** [comment]
same in mangos, better fix it there and "backport" it?

**Comment by Lillecarl** [comment]
Yeah well i saw it in mangos one, so that is why i reported it here

**Comment by Nighoo** [comment]
i've made a pullrequest at mangos https://github.com/mangos/mangos/pull/37

**Comment by VladimirMangos** [comment]
as comment in 37 pull request, this is not mangos typo and name uses as-is

**Comment by Lillecarl** [comment]
How come?:O

**Comment by Nighoo** [comment]
as vladimir said, those values are extracted from client and so should not be changed, but thanks for notice.
