### ISSUE TITLE
Scriptdev2 compile error

### ISSUE THREAD

**Issue by ryanch94** [mangosArchives/Mangos-One-server-old#26]
Won't let me post this in the scriptdev2 repo so I'll put it here.

When trying to compile scriptdev2 for mangos-one in VC2010 i get the following error.

1>------ Build started: Project: ScriptDev2, Configuration: Release Win32 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(299,5): warning MSB8004: Output Directory does not end with a trailing slash.  This build instance will add the slash as it is required to allow proper evaluation of the Output Directory.
1>  The system cannot find the path specified.
1>  Extracting revision
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppCommon.targets(151,5): error MSB6006: "cmd.exe" exited with code 3.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

The only thing i changed was the build path as it was trying to compile in C:\Users\bin\win32_release which gave me an access denied error.

**Comment by Nighoo** [comment]
compiled mangos before? without any errors?
"The system cannot find the path specified." looks like local path problem

**Comment by ryanch94** [comment]
Compiled mangoszero perfectly and mangos server fine its just scriptdev2....

**Comment by Schmoozerd** [comment]
Ensure that SD2 (version for one) is located within
<MaNGOS(one)-dir>/src/bindings/ScriptDev2
(note the big/small letters)

Also be sure to start the ScriptDev2 VC100 project by clicking the file scriptVC100.sln located in <MaNGOS>/src/bindings/ScriptDev2

Also for some nasty cases sometimes the VC compilers just fail.
You can extra force the genrevision compile, by opening the Mangos - VC100 solution file (<MaNGOS>/win/mangosdVC100.sln) and then right-click "genrevision" SElect "Project Only" and then "Build Only genrevision"

**Comment by ryanch94** [comment]
Got it working thanks :)
