### ISSUE TITLE
Error when mangosd.exe loads. Appears to still work though

### ISSUE THREAD

**Issue by ryanch94** [mangosArchives/Mangos-One-server-old#30]
When mangosd.exe finishes loading an error appears saying "The procedure entry point ?SetHover@Unit@@QAEX_N@Z could not be located in the dynamic link library mangosd.exe".

If I click ok everything seems to run ok just thought I'd point it out!

**Comment by VladimirMangos** [comment]
Possible you have outdated (build for old mangos revision) SD2 library. Just rebuild it also and error must stop reported.

**Comment by ryanch94** [comment]
Thats probably it. I didn't update scriptdev2...thanks :)

**Comment by ryanch94** [comment]
Yep, works fine now.
