### ISSUE TITLE
[Spell][Hunter][Feign Death] Issue

### ISSUE THREAD

**Issue by dimman** [mangosArchives/Mangos-One-server-old#33]
Your enemies are supposed to lose target on you after casting feign death.
Does not work at'll.

Video:
http://www.youtube.com/watch?v=R5Z98kB5B74

**Comment by fr1nge** [comment]
Are you sure you are using the latest MangosOne revision w.o any custom mods?
Works fine for me.

**Comment by Nighoo** [comment]
Selections are cleared when using Feign Death (AURA_INTERRUPT_FLAG_IMMUNE_OR_LOST_SELECTION). In addition your video does not proof anything since the caster has no target at casting.

**Comment by Lillecarl** [comment]
Nighoo, are there any possibility that this spell has some data stored in database? Because i have not modified any spell code on "my core", only stripped the database a lot. And i am the mage there, i had target on him during entire cast.

**Comment by Ve1vet** [comment]
At feign death caster lose target but... cast don't interrupts. The same issue as vanish.

**Comment by Lillecarl** [comment]
Im very surei didnt loose target, should we get a vid of that?

**Comment by Ve1vet** [comment]
Hmmm... I try fix cast interrupt about 3 month without any success( i can't get SpellEvent to interrupt it while casting ). We test everything about loosing target & cast interrupt from hunter, rogue, mage, warlock, priest, shaman. At Vanish/Stealth/FD you loosing target, but if some one cast, cast won't interrupt. Other words you have no target, but you still casting... Then spell goes to rogue/hunter ... And we all know the result :)
If now at FD caster don't lose target, then you must look up recent commits. It means something was broken not so far. Two month at most.

**Comment by ghost** [comment]
mtarget->RemoveAllAttackers(); don't work in Aura::HandleFeignDeath ?

**Comment by Lillecarl** [comment]
Must chech if any player within a range has target on him n shit!:O
