### ISSUE TITLE
compile error - conflicting declaration

### ISSUE THREAD

**Issue by icebender** [mangosArchives/Mangos-One-server-old#36]
I successfully compiled mangos-zero last year (September 2011) and so I've decided to try my luck with mangos-one. I haven't updated any of my dependencies, so maybe that's my problem. I'm using Mac OS X 10.6.8, gcc 4.2.1 and mysql 5.5.15. I don't know how to check the version of the mangos on git (I cloned it today: July 15, 2012) and I also don't know how to check my ACE version. I'm a complete novice compiler and just created my github account today, so please forgive me if I haven't formatted any of this correctly. Here is my error message:

Heron:build kyle$ sudo make -j2
[  0%] [  1%] Built target TBB_Project
Built target genrev
[  2%] Built target ACE_Project
[  3%] Built target detour
[  3%] Built target gsoap
[  9%] Built target g3dlite
[ 10%] Built target mangosscript_pch_dephelp
[ 11%] Built target framework
[ 11%] Built target revision.h
[ 12%] Built target game_pch_dephelp
[ 12%] Built target pch_Generate_mangosscript
[ 12%] Built target pch_Generate_game
[ 16%] Built target shared
[ 17%] Built target realmd
[ 17%] Building CXX object src/game/CMakeFiles/game.dir/ConfusedMovementGenerator.cpp.o
In file included from /Users/kyle/source/mangos-one/server/src/game/movement/../MoveMapSharedDefines.h:23,
                 from /Users/kyle/source/mangos-one/server/src/game/movement/../PathFinder.h:22,
                 from /Users/kyle/source/mangos-one/server/src/game/movement/MoveSplineInit.h:23,
                 from /Users/kyle/source/mangos-one/server/src/game/ConfusedMovementGenerator.cpp:23:
/Users/kyle/source/mangos-one/server/dep/recastnavigation/../recastnavigation/Detour/Include/DetourNavMesh.h:33: error: conflicting declaration ‘typedef uint64_t uint64’
/Users/kyle/source/mangos-one/server/src/framework/Platform/Define.h:112: error: ‘uint64’ has a previous declaration as ‘typedef ACE_UINT64 uint64’
make[2]: **\* [src/game/CMakeFiles/game.dir/ConfusedMovementGenerator.cpp.o] Error 1
make[1]: **\* [src/game/CMakeFiles/game.dir/all] Error 2
make[1]: **\* Waiting for unfinished jobs....
[ 75%] Built target mangosscript
make: **\* [all] Error 2

**Comment by cala** [comment]
Exact same building error, same OS, same compiler.

**Comment by cala** [comment]
Icebender, you should try the following commit: https://github.com/faramir118/mangos/commit/c542d0028445c55ccfcd6b82e69842d86c4c20bb
It fixes the conflicting declaration and allows to build Mangos One for Snow Leopard.
Thx to Faramir for the input.

**Comment by icebender** [comment]
Successful compile using faramir's commit. Thank you to cala and faramir.
