### ISSUE TITLE
Dual wielding

### ISSUE THREAD

**Issue by fr1nge** [mangosArchives/Mangos-One-server-old#38]
There is something really strange about how dual wielding works atm on One. I tested on rogues but might be the same with warriors and shamans. 
Basically you get and extra white hit whener you are damaging a target.
Something like:
MH oh oh MH oh oh MH oh oh MH MH oh MH oh oh MH MH oh MH oh MH oh oh....

Visually the character is acting normal, but somehow there are extra attacks triggered that have nothing to do with any talent or spell, they are just pure white hits.

**Comment by Ve1vet** [comment]
It's not strange. This is horrible truth :D
In one commit, i don't remember when was added support for OH weapons for mobs. Of course it was implemented in unit.cpp ( put there reset timer for Oh ). But in player.cpp they forget delete reset timer. And now for player Oh-timer resets to time faster.
Here is commit which correct this. https://gitorious.org/atlantiscore/atlantiscore/commit/afc54284312f5e38b2684e73e78162fc032c656f
Just comment or delete strings in player.cpp. Thats it.

**Comment by fr1nge** [comment]
How am i not surprised, was thinking something like that happened :p
Anyway thanks for the input, works like a charm.
Patch plus additional code style cleanups here: https://github.com/fr1nge/one.server/commit/69db65a42db4c7a575e08cd7d3e94edf5ce71e46
