### ISSUE TITLE
[bug] Fear + scatter = mob stops melee

### ISSUE THREAD

**Issue by Atari007** [mangosArchives/Mangos-One-server-old#45]
Reproduce: go inside SWP, tag the first patrolling mob with a hunter and cast fear on it. Then cast scatter shot, make sure scatter shot expires before fear. The mob will come running towards you but do no melee attacks.

How it should work: melee should be reactivated :)

Tested on mangos-one s1628

**Comment by whitegear** [comment]
Try using a warlock.  Cast fear on a mob (do not do damage as your warlock, only let your pet do damage after you have the target mob feared and running).  See if you get an identical result.

I've been having an issue where the mob will run to the pet, stand there, and do nothing until the pet slays it.  Similar to your issue I believe, perhaps hinting at a combining issue with fearaura removal/application and/or threat generation?

**Comment by overy** [comment]
The same problem with Whirlwind spell, after Boss use it he stop use meele attack
