### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Lillecarl** [mangosArchives/Mangos-One-server-old#5]
/home/mangos/src/cleanone/src/game/Level2.cpp: In member function âbool ChatHandler::HandleNpcAIInfoCommand(char_)â:
/home/mangos/src/cleanone/src/game/Level2.cpp:1531: error: must #include <typeinfo> before using typeid
make[2]: *_\* [src/game/CMakeFiles/game.dir/Level2.cpp.o] Error 1
make[1]: **\* [src/game/CMakeFiles/game.dir/all] Error 2
make: **\* [all] Error 2

I get this error on 04a4cc7ec494ba801eda768858f5e49c2d3c21b4
OS: Debian Squeeze
Compiler: gcc (Debian 4.4.5-8) 4.4.5

Tested both on my own repository and on clean one if there is anything else you would like to know then you can find me on the forums as LilleCarl

SOLUTION:
add #include <typeinfo> to the incude in Level2.cpp'

PS: Tested and compiles with both VC and GCC now :)

**Comment by VladimirMangos** [comment]
Thank you for pointing. Just not yet backported

a141cb56a472222e6d10ced58db27900f9cb7116 [11528] typeid usage req. include <typeinfo> for GCC build.

Fixed in [s1251]
