### ISSUE TITLE
No autodismount while indoor

### ISSUE THREAD

**Issue by Lillecarl** [mangosArchives/Mangos-One-server-old#6]
Hello, when you move on example mount,travel form, ghost wolf, or even flight form inside a building with the "inside flags" you dont get disformed/dismounted, but if you manually dismount you cannot mount up again
- LilleCarl

**Comment by VladimirMangos** [comment]
You sure that you not have vmap.enableIndoorCheck = false in config?
mount cast indoor checked by client, dismount at neter checked by server so if enableIndoorCheck = false
then you will see described behavior.

If this part ok then please provide .gps coordinates for problematic building.

**Comment by Lillecarl** [comment]
vmap.enableIndoorCheck = 1 i think thats true?

Map: 530 (Outland) Zone: 3483 (Hellfire Peninsula) Area: 3536 (Thrallmar)
X: 214.016388 Y: 2694.080566 Z: 90.703903 Orientation: 0.040822
grid[32,37]cell[6,0] InstanceID: 0
 ZoneX: 55.096462 ZoneY: 36.798073
GroundZ: 118.765625 FloorZ: 90.703598 Have height data (Map: 1 VMap: 1)

**Comment by VladimirMangos** [comment]
I check your coordinates and in my case auto-dismount work in One. if you have option enabled then maybe 
you not have vmap files for zone or some other vmaps option also need check. I close as not confirmed.
