### ISSUE TITLE
Compile VS 2008 issue

### ISSUE THREAD

**Issue by Ve1vet** [mangosArchives/Mangos-One-server-old#62]
Commit https://github.com/mangos-one/server/commit/90b794e03652056fbed32217603df48167f27aba
You move Battleground to separate directory but in game.vcproj you forget do this.
<Filter
            Name="BattleGround"
            >
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGround.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGround.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundAA.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundAA.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundAB.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundAB.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundAV.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundAV.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundBE.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundBE.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundEY.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundEY.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundHandler.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundMgr.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundMgr.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundNA.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundNA.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundRL.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundRL.h"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundWS.cpp"
                >
            </File>
            <File
                                RelativePath="..\..\src\game\BattleGround\BattleGroundWS.h"
                >
            </File>
Test compile? No not heard?

**Comment by Ve1vet** [comment]
Also ....\dep\include\g3dlite....\src\game; whf???

**Comment by Salja** [comment]
Thanks nust be fixed in [1693]
