### ISSUE TITLE
[Spell][Priest] Lightwell GameObject not spawning

### ISSUE THREAD

**Issue by boredtodeath** [mangosArchives/Mangos-One-server-old#63]
Hello,

Details about bug:
Priest's Lightwell ( http://www.wowhead.com/spell=724/lightwell ) doesn't create any game-object 

How it should work:
Lightwell should create a game-object out of which players could heal themselves

How to reproduce:
Clean Install
Create new priest, level to 70, try out the spell

**Comment by Salja** [comment]
http://paste2.org/p/2222586  This Patch works but need more Testing and Feedback

**Comment by boredtodeath** [comment]
Tested http://paste2.org/p/2222586 with multiple races and spell ranks, seems ok
