### ISSUE TITLE
Integrate movement maps into the core

### ISSUE THREAD

**Issue by ghost** [mangosArchives/Mangos-One-server-old#7]
[Movement maps by faramir118](https://github.com/faramir118/mangos) have reached a stage where they should be integrated into the core, to provide for a broader spectrum of people using, and testing the system.

The goal of this is to integrate a clean, usable version of movement maps into the mangos-oneo core, removing all the road bumps we may (or may not) hit while doing so.

**Comment by Lillecarl** [comment]
Indeed this should be worked on, its really some killer content, but it would be awesome if some smarthead could in some way merge all 3 map types into one, if that would be possible, i mean, are vmaps really "useful"? Couldnt the LOS be calculated from mmaps? And the maps, i dont know really what they do.... They just have to be there to get what info from?
