### ISSUE TITLE
Backport spline system

### ISSUE THREAD

**Issue by ghost** [mangosArchives/Mangos-One-server-old#8]
[mangos for WoW 3.3.5a](https://github.com/mangos/mangos/) recently received a [spline movement subsystem](https://github.com/mangos/mangos/commit/326ba2c0b634d6b5306335b9e8d7f456c61fc340).

The goal of this is to backport the **spline movement** subsystem into the mangos-zero core, removing all the road bumps we may (or may not) hit while doing so, and adapting the system to differences between WoW client 1.12 and client 3.3.5a (of which there are quite a few).

**Comment by ghost** [comment]
Work in progress

**Comment by ghost** [comment]
Great, you may also want to check the work done by [SilverIce on his mangos-one tree](https://github.com/SilverIce/mangos/tree/spline_movement_one). He did start the backport a few days ago.

**Comment by ghost** [comment]
Thanks you

**Comment by ghost** [comment]
If you need any assistance or information, just ask here.

**Comment by DomGries** [comment]
Yea lets please backport the spline system first and only then mmaps. AFAIK SilverIce already got it almost working except correct opcodes for flying movement as he said :)

**Comment by ghost** [comment]
That is the plan. I'm almost through with mmaps for mangos-zero, and would move to the spline system for mangos-one next.

**Comment by SilverIce** [comment]
I have updated my _one_  backport by adding important post spline movement commit fixes

**Comment by SilverIce** [comment]
you may add it without opcodes for flying movement. This is not part of spline movement. All spline movement related things are in game/movement/ folder.

**Comment by DomGries** [comment]
Thanks SilverIce. Added to repo in [s1389]. Only thing TODO is to find opcode for levitating as SilverIce mentioned - gonna need a TBC sniff for that :)
